CREATE TABLE perfis (
  id BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
  nome VARCHAR(200) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO perfis (nome) VALUES("ROLE_INSTRUTOR");
INSERT INTO perfis (nome) VALUES("ROLE_STARTER");
